variables:
  IMAGE_SERVER_NAME: node-app-server-image
  IMAGE_SERVER_TAG: node-app-server-image
  IMAGE_CLIENT_NAME: node-app-client-image
  IMAGE_CLIENT_TAG: node-app-client-image
  REGISTRY_USER: khanglun20000/pe_vgugroup5

stages:
  # - test
  - build

# run-frontend-tests:
#   image: node:15
#   stage: test
#   before_script:
#     - cd views/React
#     - rm -rf node_modules
#     - rm -rf package-lock.json
#     - npm install
#   script:
#     - npm test

# run-backend-tests:
#   image: node:15
#   stage: test
#   before_script:
#     - cd server
#     - cp "$TESTING_ENV_FILE" .env
#     - rm -rf node_modules
#     - rm -rf package-lock.json
#     - npm install
#   script:
#     - npm test

build-server-image:
  image: docker
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - apk add --no-cache git
    - cd server
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_SERVER_NAME:$IMAGE_SERVER_TAG .
    - docker tag $IMAGE_SERVER_NAME:$IMAGE_SERVER_TAG $REGISTRY_USER:$IMAGE_SERVER_TAG
    - docker push $REGISTRY_USER:$IMAGE_SERVER_TAG

build-client-image:
  image: docker
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - apk add --no-cache git
    - cd views/React
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_CLIENT_NAME:$IMAGE_CLIENT_TAG .
    - docker tag $IMAGE_CLIENT_NAME:$IMAGE_CLIENT_TAG $REGISTRY_USER:$IMAGE_CLIENT_TAG
    - docker push $REGISTRY_USER:$IMAGE_CLIENT_TAG