variables:
  IMAGE_NAME: khanglun20000/pe_vgugroup5
  IMAGE_SERVER_TAG: node-app-server-image
  IMAGE_CLIENT_TAG: node-app-client-image

run-frontend-tests:
  image: node:15
  stage: test
  before_script:
    - cd views/React
    - rm -rf node_modules
    - rm -rf package-lock.json
    - npm install
  script:
    - npm test

run-backend-tests:
  image: node:15
  stage: test
  before_script:
    - cd server
    - cp "$TESTING_ENV_FILE" .env
    - rm -rf node_modules
    - rm -rf package-lock.json
    - npm install
  script:
    - npm test

build-image:
  image: docker
  services:
    - docker:dind
  # variables:
  #   DOCKER_TLS_CERTDIR: "/certs"
  # before_script:
  #   - apk add --no-cache git
  #   - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE