variables:
  IMAGE_NAME: khanglun20000/pe_vgugroup5
  IMAGE_TAG: node-app-1.0

run-frontend-tests:
  image: node:15
  stage: test
  before_script:
    - cd views/React
    - rm -rf node_modules
    - rm -rf package-lock.json
    - npm install
  script:
    - npm test

run-backend-tests:
  image: node:15
  stage: test
  before_script:
    - cd server
    - cp "$TESTING_ENV_FILE" .env
    - rm -rf node_modules
    - rm -rf package-lock.json
    - npm install
  script:
    - npm test

build-image:
  image: docker:24.0.0-cli
  services:
    - docker:24.0.0-dind
  variables:
    DOCKER_TLS_CERTDIR:"/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
