run-frontend-tests:
  image: node:15
  stage: test
  before_script:
    - cd views/React
    - rm -rf node_modules
    - rm -rf package-lock.json
    - npm install
  script:
    - npm test

run-backend-tests:
  image: node:15
  stage: test
  before_script:
    - cd server
    - cp "$TESTING_ENV_FILE" .env
    - rm -rf node_modules
    - rm -rf package-lock.json
    - npm install
  script:
    - npm test

